title: Bungalow Attraction On Tide 96.0
description: Musik, neu erfunden

url: http://bungalow-attraction.de
baseurl: "/bungalow-attraction"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Über uns
   url: /about
 - title: Kontakt
   url: /contact

social:
   github: G710
   twitter:
   facebook:
   email:

google_analytics: ""
